name: Deploy Web API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2 instance..."
          scp -o StrictHostKeyChecking=no -i ${{ env.EC2_KEY }} -r ./publish/* ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/home/${{ env.EC2_USER }}/MPEA/
          ssh -o StrictHostKeyChecking=no -i ${{ env.EC2_KEY }} ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "cd /home/${{ env.EC2_USER }}/MPEA && nohup dotnet MPEA.dll > log.txt 2>&1 &"
